[package]
name = "git-sign-verifier"
version = "0.1.0"
edition = "2024"
description = "Verify git commits are signed by trusted keys"
authors = ["Colin Darie <colin@darie.eu>"]

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
git2 = "0.20.2"
