name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install libgpgme-dev
        run: sudo apt-get install -y libgpgme-dev

      - name: Build
        run: cargo build --locked --release --verbose

      - name: Run tests
        run: cargo test --locked --verbose

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-products
          path: target/release/
